site:
  title: "Ansible Automation Platform 2.7: Automation Portal and Content Lifecycle"
  start_page: automation-portal::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
